id       = "sniff-secretstore"
title    = "Whispers on the Wire"
category = "Network / Sniffing"
order    = 2
link     = "http://secretstore.local"
source   = "https://github.com/rebenkoy/les-simple-ctf/tree/master/sniff-http-secretstore"
